version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm test

      - deploy:
          name: Deploy to S3 if tests pass and branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get -y -qq update && sudo apt-get -y -qq install awscli && npm run build && aws s3 sync build s3://tttreact-hosting-mobilehub-2140333729 --delete
            else
              echo "Not master branch so not deploying"
            fi
